---

- name: Setup SSH key for hdfs slave servers
  vars: 
    master_pub_key: "{{ lookup('file', 'master_keys/' + groups['hdfs-master'][0] + '/home/' + user + '/.ssh/id_rsa.pub') }}"
  hosts: hdfs-slaves
  tasks:
  - name: Authorize the HDFS master server ssh key
    authorized_key: user="{{ user }}" key="{{ master_pub_key }}" state=present

- name: Trust the host keys
  hosts: hdfs-master
  tasks:
  - name: Trust own host key
    known_hosts:
      name: "{{ item }}"
      key: "{{ item + ' ecdsa-sha2-nistp256 ' + ansible_ssh_host_key_ecdsa_public }}"
      state: present
    with_items:
      - "0.0.0.0"
      - "{{ ansible_fqdn }}"
      - "{{ ansible_default_ipv4.address}}"

  - name: Trust the slaves host key using domain name
    known_hosts: 
      name: "{{ hostvars[item]['ansible_fqdn'] }}" 
      key: "{{ hostvars[item]['ansible_fqdn'] + ' ecdsa-sha2-nistp256 ' + hostvars[item]['ansible_ssh_host_key_ecdsa_public'] }}" 
      state: present
    with_items: "{{ groups['hdfs-slaves'] }}"

  - name: Trust the slaves host key using IP address
    known_hosts: 
      name: "{{ item }}" 
      key: "{{ item + ' ecdsa-sha2-nistp256 ' + hostvars[item]['ansible_ssh_host_key_ecdsa_public'] }}" 
      state: present
    with_items: "{{ groups['hdfs-slaves'] }}"


- name: Setup HDFS
  hosts: hdfs
  roles:
    - {role: hdfs, force_format: False}
