---

- name: stop spark
  command: "{{ spark_git_dir }}/sbin/stop-all.sh"
  when: "inventory_hostname in groups['spark-master']"
- name: start spark
  command: "nohup {{ spark_git_dir }}/sbin/start-all.sh"
  when: "inventory_hostname in groups['spark-master']"
