---

- name: Create app directory
  file: path="/home/{{ user }}/thesis" state=directory

- name: Upload and unpack the apps
  unarchive: src="thesis.tar.gz"  dest="/home/{{ user }}/thesis"

- name: Upload the data for page rank
  copy: src="soc-LiveJournal1.txt.gz" dest="/home/{{ user }}/thesis/thesis"
