---

- name: Create app directory
  file: path="/home/{{ user }}/thesis" state=directory

- name: Upload and unpack the apps
  unarchive: src="thesis.tar.gz"  dest="/home/{{ user }}/thesis"

- name: Upload text file
  copy: src="big.txt" dest="/home/{{ user }}/thesis/thesis"

