---

- name: Cloning Spark Git repository
  git:
    depth=1
    dest="{{ spark_git_dir }}"
    repo="{{ spark_git_repo }}"
    version="{{ spark_git_branch }}"

- name: Build Spark
  environment: 
    MAVEN_OPTS: "-Xmx2g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m" 
  command: mvn -DskipTests=true clean package 
  args:
    chdir: "{{ spark_git_dir }}"
  when: "build == 1"
    
- name: Update slaves
  template:
    backup=yes
    dest="{{ spark_git_dir }}/conf/slaves"
    src=slaves.j2
  notify:
    - stop spark
    - start spark

- name: Configure network interface
  template:
    backup=yes
    dest="{{ spark_git_dir }}/conf/spark-env.sh"
    src=spark-env.j2
  notify:
    - stop spark
    - start spark

- name: Configure spark-submit default
  template:
    backup=yes
    dest="{{ spark_git_dir }}/conf/spark-defaults.conf"
    src=spark-defaults.j2
  notify:
    - stop spark
    - start spark

- name: Create directory for event logging
  file: path="/tmp/spark-events" state=directory

- name: Update PATH
  lineinfile: dest="/home/{{ user }}/.profile" line="export PATH=$PATH:{{ spark_install_dir }}/spark-{{ spark_ver }}-bin-hadoop2.6/bin"
