---

- name: Add addition repository
  become: yes
  apt_repository:
    repo="{{ item }}"
  with_items:
    - 'ppa:collectd/collectd-5.5'
    #- 'deb http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    #- 'deb-src http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-security multiverse'
    - 'deb-src http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-security multiverse'
    #- 'deb http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    #- 'deb-src http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    #- 'deb http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports main restricted universe multiverse'
    #- 'deb-src http://nova.clouds.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports main restricted universe multiverse'

- name: Upgrade server packages to latest version
  become: yes
  apt: upgrade=safe update_cache=yes

- name: Install packages
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - openjdk-7-jdk
    - maven
    - git
    - collectd
    - stress-ng
    - htop
    - ntp
    - haveged
    
- name: Update host files
  become: yes
  template:
    dest=/etc/hosts
    src=hosts.j2
    backup=yes
#  lineinfile:   
#    dest=/etc/hosts 
#    regexp='.*{{ hostvars[item]['ansible_fqdn'] }}$'
#    line="{{ item }} {{ hostvars[item]['ansible_fqdn'] }}"
#    state=present
#  when: hostvars[item].ansible_fqdn is defined
#  with_items: "{{ groups['all'] }}"

- name: Update collectd configuration
  become: yes
  template:
    backup=yes
    dest="/etc/collectd/collectd.conf"
    src="collectd.j2"
  notify:
    - restart collectd
